### PR TITLE
Replace Basic Auth snippet with a complete working example

### PR DESCRIPTION
**Pull request by vog**
This working example was originally published as gist:
https://gist.github.com/mmerickel/e530f16dae61cf2960d301c7c01309b0

### CODE REVIEW

**Comment by mmerickel** [comment]
I wasn't sure if copying it wholesale would be preferable to something else but I'm fine with it if you are. In general I think we need more full working examples that are easy to tinker with like this. :-)

**Comment by stevepiercy** [comment]
There is!

```
.. gist:: https://gist.github.com/mmerickel/e530f16dae61cf2960d301c7c01309b0
```

I'll make a separate PR for the change.

**Comment by stevepiercy** [comment]
For future reference:
https://pypi.python.org/pypi/sphinxcontrib.gist

Useful for when we cannot obtain permission to reproduce remote content.

**Comment by vog** [comment]
Well, the question is where to maintain that example code.

I'm not a fan of linking to a gist from the cookbook.

I'd prefer to have it all in the `pyramid_cookbook` repository, so that future contributors have minimal friction. Also, the process then blurs: `pyramid_cookbook` pull requests can be reviewed and accepted by a group of people, while a gist usually belongs to a single problem - not a problem if the author is @mmerickel, but it is a problem in general: A future contributor might have to fork the gist if the original author is no longer active, and would have to point `pyramid_cookbook` to the fork fork, which would introduce even more friction and GitHub-specific knowledge.

If it is about being able to download the same code in a separate file, maybe put the code into a separate source file in `pyramid_cookbook` and refer to that one in the document.

**Pull request merged**
