### PR TITLE
Fix a TypeError

### PR DESCRIPTION
**Pull request by silenius**
a PosixPath cannot be used as an argument in io.open():

```
TypeError: invalid file: PosixPath('/some/file/path/static_builds/pyramid_config.json')
```

### CODE REVIEW

**Comment by stevepiercy** [comment]
@ergo would you please review this?

**Comment by ergo** [comment]
@silenius I believe this depends on the python version you use:
On python3.6 this works just fine, on 3.5 I believe you need to use `os.path.join()` there,.

```
>>> import pathlib
>>> import io
>>> f = io.open(pathlib.Path('wyniki'))
>>> f.read()
```

**Comment by silenius** [comment]
it should be that, I'm still under 3.5

**Comment by ergo** [comment]
Alternative syntax works too, so I'm approving this

**Comment by ergo** [comment]
@stevepiercy can you merge that? I don't have write access to this repo.

**Comment by stevepiercy** [comment]
Two things:

1.  If a minimum version of Python is required to use the code as is, then we need to specify that under the **Requirements** heading. Either that, or provide a commented compatible line of code, e.g.,

    ```python
    # For Python <= 3.5, use:
    # my code sample
    ```

2.  I want to make this easier to update going forward. @silenius would you please delete the `.. code-block::` section for `build_static_assets.py` from the .rst file, and replace it with:

    ```rst
    .. literalinclude:: bundling/bundling_example/bundling_example/scripts/build_static_assets.py
        :language: python
    ```

    Then we only need to update the source file. We didn't do this at first because the example source was in an external repo, but now it's hosted internally.

**Comment by stevepiercy** [comment]
Thank you!

**Pull request merged**
